{"name": "test_title_verification", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'", "trace": "self = <allure_commons._allure.fixture object at 0x0000013EB4E727B0>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n.venv\\Lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nrequest = <SubRequest 'log_on_failure' for <Function test_title_verification>>\n\n    @pytest.fixture()\n    def log_on_failure(request):\n        yield\n        item=request.node\n>       if item.rep_call.failed:\nE       AttributeError: 'Function' object has no attribute 'rep_call'\n\ntest_cases\\conftest.py:20: AttributeError"}, "attachments": [{"name": "log", "source": "2c82d4e9-b93d-476c-9b16-5d5d3c83e5b7-attachment.txt", "type": "text/plain"}], "start": 1741258539781, "stop": 1741258541065, "uuid": "933c8860-a103-46e9-99fa-770bebe8585d", "historyId": "e22bd92f4e5e05b86e134f7dacdb4909", "testCaseId": "e22bd92f4e5e05b86e134f7dacdb4909", "fullName": "test_admin_login.Test_01_Admin_Login#test_title_verification", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "suite", "value": "test_admin_login"}, {"name": "subSuite", "value": "Test_01_Admin_Login"}, {"name": "host", "value": "Sadat"}, {"name": "thread", "value": "8448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_admin_login"}]}